//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetirementHome
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contact
    {
        [Required]
        public int Id { get; set; }
        [Required(ErrorMessage = "The First Name cannot be blank"), MaxLength(10)]
        [Display(Name = "First Name")]
        public string First_Name { get; set; }
        [Required(ErrorMessage = "The Last Name cannot be blank"), MaxLength(10)]
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }
        [Required(ErrorMessage = "Email cannot be blank"), MaxLength(20)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Email is not valid.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Phone cannot be blank"), MaxLength(11), Phone]
        public string Phone { get; set; }
        [Required(ErrorMessage = "Address cannot be blank"), MaxLength(100)]
        public string Address { get; set; }
        [Required(ErrorMessage = "Comment cannot be blank"), MaxLength(100)]
        public string Comment { get; set; }
    }
}
